### PR TITLE
Version detection problem

### PR DESCRIPTION
**Pull request by CrafterSvK**
I had a problem with version detection because 12.99.1 is not a number, so it cannot be compared. Removed revision number using sed and removed a grep portion for faster execution.

### CODE REVIEW

**Comment by graysky2** [comment]
This code fails on the current stable (12.2).
```pactl --version | sed -ne 's/pactl \([0-9]\+.[0-9]\+\).\+/\1/p'```

vs

```
pactl --version | grep pactl | pactl --version | grep pactl | sed -e 's/^pactl //' -e 's/\([0-9.]\+\).*/\1/'
12.2
```

**Comment by CrafterSvK** [comment]
I made a mistake in a wildcard replaced + with *. Now it should work.

**Comment by CrafterSvK** [comment]
> I made a mistake in a wildcard replaced + with *. Now it should work.

Works on "pactl 12.99.2-3-g493e". ArchLinux.

**Comment by CrafterSvK** [comment]
Problem resolved, thanks

**Pull request closed without merging**
