### PR TITLE
Updated to work with Pulseaudio 14

### PR DESCRIPTION
**Pull request by augustin64**
I have updated `refreshcurvol` and `refreshsrcvol` to work with pulseaudio 5

### CODE REVIEW

**Comment by graysky2** [comment]
Is any distro actually shipping v5 which is over 6 years old now???

**Comment by augustin64** [comment]
I made a mistake, i've updated it to Pulseaudio 14 (which I'm actually using) but wrote 5 because of the code comments

**Comment by graysky2** [comment]
I am using 14.2 and don't see ill-effects using the code as-is.  What does your PR fix exactly?

**Comment by augustin64** [comment]
It is maybe an issue on my laptop only, but here is the problem : 
```
➜  ~ ./pulseaudio-ctl.in up 2
./pulseaudio-ctl.in: ligne 194: 2 +   : erreur de syntaxe : opérande attendu (le symbole erroné est « +   »)
```
I've done many tests and `$CURVOL` seems not to have any value, the PR I propose is what I've tried to fix for me (but is maybe only my issue)

**Comment by augustin64** [comment]
Output of `./pulseaudio-ctl.in full-status` (original version)
`no no`
Output of `pulseaudio-ctl full-status` (my modified version)
` 52 no no`

**Comment by graysky2** [comment]
I wonder if it's a locale issue... can you try https://github.com/graysky2/pulseaudio-ctl/commit/47a6e681812245d915c02a2ad98143bc1200bc82 (not your modified code) and let me know if the function works?

**Comment by augustin64** [comment]
Stills not working

**Comment by graysky2** [comment]
Can you post the output of: `pacmd list-sinks`

**Comment by augustin64** [comment]
Output of `pacmd list-sinks`  :  
```
➜  ~ pacmd list-sinks   
2 sink(s) available.
    index: 0
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo>
	driver: <module-alsa-card.c>
	flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE
	priority: 9039
	volume: front-left: 34079 /  52% / -17,04 dB,   front-right: 34079 /  52% / -17,04 dB
	        balance 0,00
	base volume: 65536 / 100% / 0,00 dB
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max request: 0 KiB
	max rewind: 0 KiB
	monitor source: 0
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Stéréo
	used by: 0
	linked by: 1
	configured latency: 0,00 ms; range is 0,50 .. 1837,50 ms
	card: 0 <alsa_card.pci-0000_00_1b.0>
	module: 6
	properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "ALC269VB Analog"
		alsa.id = "ALC269VB Analog"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xf7918000 irq 32"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1b.0"
		sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "1e20"
		device.product.name = "7 Series/C216 Chipset Family High Definition Audio Controller"
		device.form_factor = "internal"
		device.string = "front:0"
		device.buffering.buffer_size = "352800"
		device.buffering.fragment_size = "176400"
		device.access_mode = "mmap+timer"
		device.profile.name = "analog-stereo"
		device.profile.description = "Stéréo analogique"
		device.description = "Audio interne Stéréo analogique"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	ports:
		analog-output-speaker: Speakers (priority 10000, latency offset 0 usec, available: unknown)
			properties:
				device.icon_name = "audio-speakers"
		analog-output-headphones: Headphones (priority 9900, latency offset 0 usec, available: no)
			properties:
				device.icon_name = "audio-headphones"
	active port: <analog-output-speaker>
  * index: 1
	name: <noechosink>
	driver: <module-echo-cancel.c>
	flags: HW_MUTE_CTRL LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE
	priority: 1000
	volume: mono: 34079 /  52%
	        balance 0,00
	base volume: 65536 / 100%
	volume steps: 65537
	muted: no
	current latency: 0,00 ms
	max request: 0 KiB
	max rewind: 0 KiB
	monitor source: 3
	sample spec: float32le 1ch 32000Hz
	channel map: mono
	             Mono
	used by: 0
	linked by: 0
	configured latency: 0,00 ms; range is 0,50 .. 1837,50 ms
	module: 23
	properties:
		device.master_device = "alsa_output.pci-0000_00_1b.0.analog-stereo"
		device.class = "filter"
		device.intended_roles = "phone"
		device.description = "Audio interne Stéréo analogique (echo cancelled with Audio interne Stéréo analogique)"
		device.icon_name = "audio-card"
```
I use an echo canceler module because my micro was awful, it is maybe in cause of this problem

**Comment by graysky2** [comment]
Can you try https://github.com/graysky2/pulseaudio-ctl/commit/2f4fc3b270ba97d263b77d79db60d9990e19c65e

**Comment by augustin64** [comment]
Works !

**Pull request closed without merging**
