### PR TITLE
New Feature: Set mute status

### PR DESCRIPTION
**Pull request by somini**
Defaults to toggle, so backwards-compatibility is maintained.

### CODE REVIEW

**Comment by somini** [comment]
This supersedes #41

**Comment by graysky2** [comment]
The goal of a mute button is to mute/umute depending on the current status.  I don't see why this PR is needed.  What is the use-case for this?

**Comment by somini** [comment]
At least for me, when I lock the screen I want my sound to be muted so that there can't be any surprises when leaving my computer unattended. Seems wasteful to have yet another way to do it.

**Comment by Philosoft** [comment]
I feel like `plusone` isn't enough here. I have the very same use case: leaving machine and invoking `xscreensaver-command -lock`. It'd be really superhelpful to merge this. As far as I can tell, this PR even do not break anything. So, can we have it @graysky2 ? Pretty please?

**Comment by graysky2** [comment]
Seems reasonable.

**Pull request merged**
